# Generated by Django 3.1.1 on 2020-09-04 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(blank=True)),
                ('duration', models.DurationField(blank=True)),
                ('activity', models.CharField(max_length=200)),
            ],
        ),
    ]
