# Generated by Django 3.1.1 on 2020-09-07 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stopwatch', '0002_record_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='duration',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='record',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
