# Generated by Django 3.1.1 on 2020-09-07 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stopwatch', '0003_auto_20200906_2229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='start_time',
            new_name='start',
        ),
    ]
